<?php

/**
 * @file
 * Contains tito.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tito_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tito module.
    case 'help.page.tito':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tito') . '</p>';
      return $output;
  }
}
